// Registry of published content. Add a new entry here to list another app
// or article — no other changes needed as long as it lives under its own
// folder with its own index.html. `category` must match an id in
// categories.js so the item shows up on the right category page.
const APPS = [
  {
    name: "MD → Confluence 変換窓口",
    description: "Markdownや既存ページを、Confluenceにレイアウトごと貼り付けられる形に変換します。「書式付きでコピー」なら見出し・表・コードブロックが本来の形で入ります。サーバー通信なしでその場で完結。",
    path: "apps/md2confluence.html",
    icon: "📐",
    category: "mini-apps",
  },
  {
    name: "生成AIのしくみ入門",
    description: "文章生成AI・画像/動画生成AIが答えを作る仕組みを、専門知識なしでも図解でわかるように解説します。",
    path: "apps/generative-ai-basics-guide/",
    icon: "🧠",
    category: "ltx",
  },
  {
    name: "GitHub用語辞典",
    description: "Repository・Commit・Push・Pullなど、GitHub初心者がつまずきやすい用語をやさしく解説します。",
    path: "github-glossary.html",
    icon: "📖",
    category: "github",
  },
  {
    name: "GitHubの一般的なデプロイ方法",
    description: "GitHub Pages・GitHub Actions・外部ホスティングサービスなど、代表的なデプロイ方法を初心者向けに紹介します。",
    path: "github-deploy-guide.html",
    icon: "🚢",
    category: "github",
  },
  {
    name: "Next.js+Prisma+Geminiで漫画ジェネレーターを作った話",
    description: "あらすじからコマ割りを自動生成するアプリの、DB設計・AI生成・SVGコンテ生成・PWA対応までの手順を図解でまとめました。おまけでVercelデプロイのつまずきも紹介します。",
    path: "apps/nextjs-vercel-deploy-story/",
    icon: "📖",
    category: "github",
  },
  {
    name: "pip コマンド一覧",
    description: "install・uninstall・list・freezeなど、Pythonのパッケージ管理でよく使うpipコマンドをまとめました。",
    path: "pip-commands.html",
    icon: "📦",
    category: "python",
  },
  {
    name: "AI画像・動画生成を支えるPythonライブラリまとめ",
    description: "PyTorch・Transformers・Diffusers・CUDA・xFormersなど、ComfyUIやLTX・FLUX系のソースコードに登場するライブラリを役割ごとに整理しました。",
    path: "ai-python-libraries.html",
    icon: "🐍",
    category: "python",
  },
  {
    name: "関数電卓",
    description: "Desmos風のグラフ電卓。複数の数式を色分けして描画し、パン・ズームで自由に表示範囲を変えられます。",
    path: "apps/graph-calculator/",
    icon: "📈",
    category: "mini-apps",
  },
  {
    name: "動画AI LTX-2.3のしくみ入門",
    description: "latent・conditioning・guide・IC-LoRAといったキーワードから、動画生成AIのしくみを初心者向けに図解で解説します。",
    path: "apps/ltx2-video-ai-guide/",
    icon: "🎬",
    category: "ltx",
  },
  {
    name: "生成AI用語",
    description: "蒸留・量子化など、画像・動画生成AIの記事でよく見かける用語をやさしく解説します。",
    path: "generative-ai-glossary.html",
    icon: "🧠",
    category: "ltx",
  },
  {
    name: "画像生成AIパイプライン解説",
    description: "CLIP・VAE・U-Netの役割と関係、データフローの流れを図解で整理します。",
    path: "image-ai-pipeline.html",
    icon: "🖼️",
    category: "ltx",
  },
  {
    name: "HLSL マテリアルエディタ",
    description: "UEのCustomノード風にHLSLを書くと、球やキューブにリアルタイム反映されます。ライトベクターなどの組み込み変数とパラメータ調整つき。",
    path: "apps/hlsl-material-editor/",
    icon: "🎨",
    category: "mini-apps",
  },
  {
    name: "8ビット シューティングゲーム",
    description: "懐かしのドット絵スタイル。敵を撃ってスコアを稼ぎましょう。矢印キーで移動、スペースで射撃。",
    path: "apps/8bit-shooting-game/",
    icon: "🎮",
    category: "mini-apps",
  },
  {
    name: "ローカルLLMチャット",
    description: "ローカル実行のLLM（OllamaやLM Studio等）と会話するシンプルなチャットアプリ。TinyLlamaやPhiなどの軽量モデルでお試しください。",
    path: "apps/local-llm-chat/",
    icon: "🤖",
    category: "mini-apps",
  },
  {
    name: "LTXプロンプトジェネレーター",
    description: "日本語で入力するだけで、LTX-2.3/2.5の公式ガイドに沿った英語プロンプトをブラウザ内AI（WebLLM）が組み立てます。サーバー・APIキー不要。",
    path: "apps/ltx-prompt-generator/",
    icon: "✍️",
    category: "ltx",
  },
  {
    name: "動画生成用タイムラインWeb UI 技術仕様書",
    description: "ComfyUIを実行エンジンとして使い、タイムラインUIを備えた独自Webフロントエンドを構築するための技術仕様書です。",
    path: "apps/comfyui-timeline-webui-spec/",
    icon: "🎞️",
    category: "comfyui",
  },
  {
    name: "絵コンテ生成ツール 技術仕様書",
    description: "字コンテから絵コンテを生成し、動画生成AIに渡すプロンプトと参照画像のセットを出力するWebアプリケーションの技術仕様書です。",
    path: "apps/storyboard-tool-spec/",
    icon: "🎨",
    category: "ltx",
  },
  {
    name: "ComfyUIをAPIだけで使う方法 対話まとめ",
    description: "標準UIを使わずAPIだけでComfyUIを動かす方法、ワークフローのAPI形式エクスポート、通信を絞るファイアウォール設定などについての対話をまとめました。",
    path: "apps/comfyui-api-talk/",
    icon: "💬",
    category: "comfyui",
  },
  {
    name: "ComfyUI App Builder、結局どう使う？",
    description: "App Builderの使い方や共有の仕組み、想定される使い所、カスタムウィジェットとの相性についての対話をQ&A形式でまとめました。",
    path: "apps/comfyui-app-builder-talk/",
    icon: "🧩",
    category: "comfyui",
  },
  {
    name: "ComfyUI ワークフロー クリーナー",
    description: "残したい出力ノードを1つ選ぶだけで、そこに繋がっていない未接続・未使用のノードを丸ごと削除し、きれいなワークフローJSONを作れます。",
    path: "apps/comfyui-workflow-cleaner/",
    icon: "🧹",
    category: "comfyui",
  },
  {
    name: "UEマテリアル小技:EyeAdaptationで暗所グロー",
    description: "EyeAdaptationノードで、EmissiveColorを除算して露出変化と相殺しつつ暗所だけ加算で光を足すマテリアルの組み方を解説します。",
    path: "apps/ue-eyeadaptation-darkglow/",
    icon: "🧱",
    category: "ue",
  },
  {
    name: "UEマテリアル小技:白飛びを飼いならす3つの技",
    description: "Emissiveがすぐ真っ白になる悩みを、カスタムトーンカーブ・Kelvin色温度・独自Bloomの3技法で解決する方法を博士と助手の対話形式で解説します。",
    path: "apps/ue-highlight-control-techniques/",
    icon: "✨",
    category: "ue",
  },
  {
    name: "UEマテリアル小技:台形カーブによるRチャンネル走査デバッグ表示",
    description: "Rチャンネルの256階調をTimeで走査し、一致する階調だけを台形カーブでsaturateのみを使って浮かび上がらせるデバッグ表示の作り方をまとめました。",
    path: "apps/ue-rchannel-scan-debug/",
    icon: "📶",
    category: "ue",
  },
  {
    name: "HoudiniでObjectレベルのHDAをSOPレベルに変換する方法",
    description: "うっかりObjectレベルでHDA化してしまった部品を、SOPレベルの部品として作り直す2つの方法を図解でまとめます。",
    path: "apps/houdini-object-to-sop-hda/",
    icon: "🎛️",
    category: "houdini",
  },
  {
    name: "セッションログ運用ワークフロー(GitHub Copilot向け)",
    description: "LLMとの作業で得た気づき・躓いた点と対処法を蓄積し、次回セッションで再利用するための運用ルールをテンプレ付きでまとめました。",
    path: "apps/session-log-workflow-guide.html",
    icon: "🤖",
    category: "ai-coding",
  },
  {
    name: "Claude Design × Git Copilot で進めるUIモック作成ワークフロー",
    description: "「仕様書 → モック → 実装」をAIで効率化する2AI連携フローと、実際に使ったプロンプトをまとめました。",
    path: "apps/claude-design-git-copilot-workflow.html",
    icon: "🎨",
    category: "ai-coding",
  },
  {
    name: "Markdown記法ガイド",
    description: "見出し・リスト・リンクからテーブル・脚注まで、Markdownの書き方を簡単なものから順にまとめました。",
    path: "markdown-guide.html",
    icon: "📝",
    category: "markdown",
  },
  {
    name: "MiniMax H3をComfyUIで動かす環境構築",
    description: "動画・音声同時生成モデルMiniMax H3のベースモデル選定からTurbo LoRAによる高速化、速度の目安までまとめました。",
    path: "minimax-h3-comfyui-setup.html",
    icon: "⚙️",
    category: "minimax-h3",
  },
  {
    name: "ローカルMiniMax H3 R2V ComfyUI構成まとめ",
    description: "RTX5080(16GB)・参照画像多用のR2V用途向けに、DiT/VAE/テキストエンコーダー/Turbo LoRAの選定理由を決定ログ付きでまとめました。",
    path: "minimax-h3-r2v-comfyui-setup.html",
    icon: "🖼️",
    category: "minimax-h3",
  },
  {
    name: "絵コンテ→動画の追従性を上げたい: MiniMax H3のControlNet活用を検討したログ",
    description: "絵コンテのラフな構図をR2V生成に反映させる方法を検討し、Alibaba PAI製のMiniMax-H3-Fun-Controlnet-Unionという前例にたどり着くまでのログです。",
    path: "minimax-h3-storyboard-control.html",
    icon: "🎬",
    category: "minimax-h3",
  },
  {
    name: "npm audit の使い方",
    description: "npm auditで既知の脆弱性を検出し、npm audit fixで修正する基本コマンドと注意点をまとめました。",
    path: "npm-audit-guide.html",
    icon: "🟨",
    category: "javascript",
  },
  {
    name: "JSのライブラリ管理とnpm auditにまつわる対話まとめ",
    description: "npmとpipの違い、AIにライブラリを追加させる不安、Node.js本体とnode_modulesの関係についての対話をまとめました。",
    path: "apps/js-library-management-talk/",
    icon: "📦",
    category: "javascript",
  },
  {
    name: "ComfyUIカスタムノードのセキュリティ、どうチェックする?",
    description: "カスタムノードが抱えるリスクと、依存パッケージ・危険な関数呼び出しをチェックする実践的なワークフローをまとめました。自作スキャナーのダウンロード付き。",
    path: "comfyui-custom-node-security.html",
    icon: "🛡️",
    category: "comfyui",
  },
  {
    name: "Substance Designer × AI自動化 調査まとめ",
    description: "ピクセルプロセッサー内部の関数グラフをAIに自動生成させる検証。MCPサーバーの限界を踏まえ、Substance Automation Toolkit(pysbs)を使う方針に至った調査経緯をまとめました。",
    path: "substance-designer-ai-automation.html",
    icon: "🎨",
    category: "substance-designer",
  },
];
